script:
- BALLERINA_VERSION="${VERSION:-0.982.0}"
- echo -e "\033[36m${BALLERINA_VERSION}\033[m"

- DISTRIBUTION_NAME=ballerina-platform-$BALLERINA_VERSION
- echo -e "\033[36m${DISTRIBUTION_NAME}\033[m"

- DOWNLOAD_CHANNEL="${CHANNEL:-downloads}"
- echo -e "\033[36m${DOWNLOAD_CHANNEL}\033[m"

- DOWNLOAD_LOCATION="${URL:-https://product-dist.ballerina.io}"
- echo -e "\033[36m${DOWNLOAD_LOCATION}\033[m"

- echo -e "\033[36m$DOWNLOAD_LOCATION/$DOWNLOAD_CHANNEL/$BALLERINA_VERSION/$DISTRIBUTION_NAME.zip\033[m"
- wget $DOWNLOAD_LOCATION/$DOWNLOAD_CHANNEL/$BALLERINA_VERSION/$DISTRIBUTION_NAME.zip

- unzip -q $DISTRIBUTION_NAME.zip

- export PATH=$PATH:$(pwd)/$DISTRIBUTION_NAME/bin

- ballerina version

- cd hom/reservation

- ballerina init

- ballerina build